import { describe, it, expect } from "vitest";
import { SMALL_COMBOS, smallComboRows } from "./small-cluster-combos";

describe("SMALL_COMBOS catalogue", () => {
  it("covers the 13 small enchantments that carry notables", () => {
    // 16 small enchantments exist; dexterity, intelligence and strength have
    // no notables to search for. Generated by poestash's
    // scripts/gen-small-cluster-combos.ts.
    expect(SMALL_COMBOS.length).toBe(146);
    expect(new Set(SMALL_COMBOS.map((c) => c.enchantmentTag)).size).toBe(13);
  });

  it("carries a trade stat id for every combo", () => {
    // A combo with no stat id would search for nothing and seed a row that
    // never prices.
    const bad = SMALL_COMBOS.filter(
      (c) => !/^explicit\.stat_\d+$/.test(c.tradeStatId),
    );
    expect(bad).toEqual([]);
  });
});

describe("smallComboRows", () => {
  const combos = [
    {
      enchantmentTag: "affliction_armour",
      notableName: "Enduring Composure",
      tradeStatId: "explicit.stat_2043284086",
    },
  ];

  it("keys the row on the notable's name", () => {
    // The table's combo_key is the " + "-joined notable list, and a small
    // cluster's list is one name long.
    expect(smallComboRows("Allflame", combos)).toEqual([
      {
        league: "Allflame",
        enchantment_tag: "affliction_armour",
        jewel_size: "small",
        combo_key: "Enduring Composure",
        notable_names: ["Enduring Composure"],
        trade_stat_ids: ["explicit.stat_2043284086"],
      },
    ]);
  });

  it("leaves the JSONB values as arrays", () => {
    // postgres.js stringifies JSONB parameters itself. Pre-stringifying here
    // would store the JSON *string* `"[\"x\"]"` and break every reader.
    const [row] = smallComboRows("Allflame", combos);
    expect(Array.isArray(row.notable_names)).toBe(true);
    expect(Array.isArray(row.trade_stat_ids)).toBe(true);
  });
});
